version: "3.7"

services:
  app:
    build: .
    container_name: app_ignite
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/usr/app
    environment:
      APP_PORT: ${APP_PORT}
      DB_HOST: ${DB_CONTAINER_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - db
    links:
      - db
    
  db: 
    image: postgres
    container_name: db_ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata: